Implementation added
joej0e/ConcatenatedWordsFinder pull request #1
Opened 2020-02-04 13:04 UTC by joej0e

2020-02-04 13:09 UTC, boroda4436 requested changes

2020-02-04 13:09 UTC, boroda4436 commented on src/main/java/Main.java
> +    private static String[] findConcatenatedWords(String fileName) throws IOException {
@joej0e can we decompose this method?
please write some unit tests and refactor the solution at the same time

2020-02-05 11:59 UTC, boroda4436 requested changes

2020-02-05 11:59 UTC, boroda4436 commented on src/main/java/Main.java
> +        String[] result = WordsProcessingUtils.findLongestConcatenatedWords(fileName);
```suggestion
        SomeClassThatRepresentTheResult  data = WordsProcessingUtils.findLongestConcatenatedWords(fileName);
```
повертати масив не зовсім круто. Не зрозуміло що означає result[0] а що означає result[2] і яка між ними різниц. Рекомендую створити окремий клас в якому будуть описані результати роботи алгоритму

2020-02-05 11:59 UTC, boroda4436 commented on src/main/java/utils/WordsProcessingUtils.java
> +    public static String[] findLongestConcatenatedWords(String fileName) throws IOException {
@joej0e статика це погано) Коли в тебе апплікейшн буде розростатися і в тебе буде DI - статику буде дуже важко мокати в тестах. Давай ми приберемо статику?)

2020-02-05 11:59 UTC, boroda4436 commented on src/main/java/utils/WordsProcessingUtils.java
> +    private static List<String> createWordsList(String fileName) throws IOException {
```suggestion
  List<String> createWordsList(String fileName) throws IOException {
```
Давай приберемо _private_ - тоді ми зможемо покрити цей метод в тестах
Приберемо _static_ - причину вказував вище)

2020-02-05 11:59 UTC, boroda4436 commented on src/main/java/utils/WordsProcessingUtils.java
> +    private static List<String> createConcatenatedWordsSortedArray(List<String> words) {
```suggestion
   List<String> createConcatenatedWordsSortedArray(List<String> words) {
```

2020-02-05 11:59 UTC, boroda4436 commented on src/main/java/utils/WordsProcessingUtils.java
> +    private static List<String> createConcatenatedWordsSortedArray(List<String> words) {
@joej0e + загальна рекомендація. При запуску тестів - рекомендую запустити в режимі Run with Coverage і добитися щоб як мінімум 95% строк було покрито тестами

2020-02-07 20:56 UTC, boroda4436 commented on concatenatedListTest
> +car mar war tor
Should be in the test resource folder

2020-02-08 07:07 UTC, boroda4436 commented on pom.xml
>  </project>
add empty line

2020-02-08 07:47 UTC, boroda4436 requested changes

2020-02-08 07:47 UTC, boroda4436 commented on src/main/java/ConcatenatedWordsSortedList.java
> +    private List<String> concatenatedWords;
@joej0e can we make this class stateless?

2020-02-08 07:47 UTC, boroda4436 commented on src/main/java/ConcatenatedWordsSortedList.java
> +    public class FirstAndSecondLongestWordAndSize {
@joej0e too much 'and' in the name. Can we rename this class? For example LongestConcatenatedWordsDto

2020-02-08 07:47 UTC, boroda4436 commented on src/test/java/MainTest.java
> +public class MainTest {
@joej0e test class name must conform to the convention  https://mate-academy.github.io/style-guides/java/java.html#s5.2.2-class-names

2020-02-08 07:47 UTC, boroda4436 commented on src/test/java/MainTest.java
> +    public void assertVoidFileNameThrowsFileNotFoundException() {
what means void in this method name?

2020-02-08 07:47 UTC, boroda4436 commented on src/test/java/MainTest.java
> +
remove redundant empty lines

2020-02-08 07:47 UTC, boroda4436 commented on src/test/java/MainTest.java
> +        fileWriter.write("do car war carwar docarwar");
@joej0e are you clearing the file after each method execution?

2020-02-08 07:47 UTC, boroda4436 commented on src/test/java/MainTest.java
> +
@joej0e what is the percentage of unit test code coverage?

2020-02-08 07:47 UTC, boroda4436 commented on src/main/java/ConcatenatedWordsSortedList.java
> +    private List<String> createConcatenatedWordsSortedList(List<String> words) {
```suggestion
   List<String> createConcatenatedWordsSortedList(List<String> words) {
```
lets make it default and cover with unit tests

2020-02-08 07:47 UTC, boroda4436 commented on src/main/java/ConcatenatedWordsSortedList.java
> +        return new FirstAndSecondLongestWordAndSize();
why we need this return of new object?

2020-02-11 12:11 UTC, boroda4436 requested changes

2020-02-11 12:11 UTC, boroda4436 commented on src/main/java/Main.java
> +                concatenatedWordsSortedList.new LongestConcatenatedWordsDto(fileName);
@joej0e виглядає трохи складнувато. Чому б не повернути LongestConcatenatedWordsDto в результаті виконання методу?

2020-02-11 12:11 UTC, boroda4436 commented on src/main/java/ConcatenatedWordsSortedList.java
> +    private List<String> createConcatenatedWordsSortedList(List<String> words) {
@joej0e чому проігнорувала цей комент?

2020-02-11 12:11 UTC, boroda4436 commented on src/main/java/ConcatenatedWordsSortedList.java
> +    private List<String> getConcatenatedWordsSortedList(String fileName) throws IOException {
```suggestion
    List<String> getConcatenatedWordsSortedList(String fileName) throws IOException {
```

2020-02-13 14:48 UTC, Sofasmile approved these changes

2020-02-14 08:45 UTC, merged